
<%= envfilepath = '/home/dotcloud/environment.json' %>
<%= environment = JSON.parse(File.open(envfilepath).read()) %>



development:
  host: localhost
  database: railsjot_development

test:
  host: localhost
  database: railsjot_test

# set these environment variables on your prod server
production:
  host: <%= environment["DOTCLOUD_DB_MONGODB_HOST"] %>
  port: <%= environment["DOTCLOUD_DB_MONGODB_PORT"] %>
  username: "root"
  password: <%= environment["DOTCLOUD_DB_MONGODB_PASSWORD"] %>
  database: db1
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  #


