
development:
  host: localhost
  database: railsjot_development

test:
  host: localhost
  database: railsjot_test

# set these environment variables on your prod server
production:
  host: <%= ENV["DOTCLOUD_DB_MONGODB_HOST"] %>
  port: <%= ENV["DOTCLOUD_DB_MONGODB_PORT"] %>
  username: root
  password: <%= ENV["DOTCLOUD_DB_MONGODB_PASSWORD"] %>
  database: admin
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  #


